name: Traffic Generator Perbaikan

on:
  workflow_dispatch: # Pemicu manual saja

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Google Chrome Terbaru
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium undetected-chromedriver webdriver-manager

      - name: Execute Bot
        run: |
          export PYTHONUNBUFFERED=1
          python bot.py
